export const categories = [
    { key: 'purchases', name: 'Compras', icon: 'shopping-bag', color: '#5636D3' },
    { key: 'food', name: 'Alimentação', icon: 'coffee', color: '#FF872C' },
    { key: 'salaryF', name: 'Salario Final', icon: 'dollar-sign', color: '#12A454' },
    { key: 'salaryQ', name: 'Salario Quinzenal', icon: 'dollar-sign', color: '#12A454' },
    { key: 'aposentadoria', name: 'INSS', icon: 'dollar-sign', color: '#12A454' },
    { key: 'freelance', name: 'LM', icon: 'dollar-sign', color: '#12A454' },
    { key: 'hospedagem', name: 'Hospedagem', icon: 'dollar-sign', color: '#12A454' },
    { key: 'decimoterceiro1', name: '13º Salario', icon: 'dollar-sign', color: '#12A454' },
    { key: 'decimoterceiro2', name: '13º Aposentadoria', icon: 'dollar-sign', color: '#12A454' },
    { key: 'car', name: 'Carro', icon: 'crosshair', color: '#E83F5B' },
    { key: 'leisure', name: 'Lazer', icon: 'heart', color: '#26195C' },
    { key: 'studies', name: 'Estudos', icon: 'book', color: '#9C001A' },
    { key: 'villalobos', name: 'Villa Lobos', icon: 'book', color: '#8B008B' },
    { key: 'kvt', name: 'Pagamentos KVT', icon: 'book', color: '#DB7093' },
    { key: 'cartaocreditoP', name: 'Cartão Porto', icon: 'book', color: '#8A2BE2' },
    { key: 'cartaocreditoB', name: 'Cartão Bradesco', icon: 'book', color: '#8A2BE2' },
    { key: 'cesta', name: 'Cesta Basica', icon: 'book', color: '#3CB371' },
    { key: 'empregadaQ', name: 'Empregada Quinzena', icon: 'book', color: '#3CB371' },
    { key: 'empregadaM', name: 'Empregada Mensal', icon: 'book', color: '#3CB371' },
    { key: 'diversos', name: 'Diversos', icon: 'book', color: '#FF7F50' },
]; 