export const categories = [
    { key: 'purchases', name: 'Compras', icon: 'shopping-bag', color: '#5636D3' },
    { key: 'food', name: 'Alimentação', icon: 'coffee', color: '#FF872C' },
    { key: 'salary30', name: 'Salario Final Avanade', icon: 'dollar-sign', color: '#12A454' },
    { key: 'salary15', name: 'Salario Quinzenal Avanade', icon: 'dollar-sign', color: '#12A454' },
    { key: 'aposentadoria', name: 'INSS', icon: 'dollar-sign', color: '#12A454' },
    { key: 'freelance', name: 'LA', icon: 'dollar-sign', color: '#12A454' },
    { key: 'hospedagem1', name: 'Fitwellness - manutenção', icon: 'dollar-sign', color: '#12A454' },
    { key: 'hospedagem2', name: 'Sinos - manutenção', icon: 'dollar-sign', color: '#12A454' },
    { key: 'decimoterceiro1', name: '13º Salario Avanade', icon: 'dollar-sign', color: '#12A454' },
    { key: 'decimoterceiro2', name: '13º Aposentadoria', icon: 'dollar-sign', color: '#12A454' },
    { key: 'car', name: 'Carro', icon: 'crosshair', color: '#E83F5B' },
    { key: 'leisure', name: 'Lazer', icon: 'heart', color: '#26195C' },
    { key: 'studies', name: 'Estudos', icon: 'book', color: '#9C001A' },
    { key: 'villalobos', name: 'Villa Lobos', icon: 'book', color: '#9C001A' },
    { key: 'kvt', name: 'Pagamentos KVT', icon: 'book', color: '#9C001A' },
    { key: 'cartaocreditoP', name: 'Cartão de Crédito Porto', icon: 'book', color: '#9C001A' },
    { key: 'cartaocreditoB', name: 'Cartão de Crédito Bradesco', icon: 'book', color: '#9C001A' },
    { key: 'cesta', name: 'Cesta Basica', icon: 'book', color: '#9C001A' },
    { key: 'goreteq', name: 'Gorete Quinzena', icon: 'book', color: '#9C001A' },
    { key: 'goretem', name: 'Gorete Mensal', icon: 'book', color: '#9C001A' },
]; 